// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfEQcigtZ5n-DYJmgklEjKudDdjbGSGc',
    appId: '1:111912410978:web:481407c5e99a286310d63b',
    messagingSenderId: '111912410978',
    projectId: 'btlnhom15',
    authDomain: 'btlnhom15.firebaseapp.com',
    storageBucket: 'btlnhom15.firebasestorage.app',
    measurementId: 'G-3RL2JL47Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn9i4p4HiYjbVfgaBGXrDUZsJqCh-RFRc',
    appId: '1:111912410978:android:5fc565d402d33c7b10d63b',
    messagingSenderId: '111912410978',
    projectId: 'btlnhom15',
    storageBucket: 'btlnhom15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPC1vujBXQWS77NjjhrtqbC3KwN-Qgrjo',
    appId: '1:111912410978:ios:98983be9e262e94010d63b',
    messagingSenderId: '111912410978',
    projectId: 'btlnhom15',
    storageBucket: 'btlnhom15.firebasestorage.app',
    iosBundleId: 'com.example.btlNhom15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPC1vujBXQWS77NjjhrtqbC3KwN-Qgrjo',
    appId: '1:111912410978:ios:98983be9e262e94010d63b',
    messagingSenderId: '111912410978',
    projectId: 'btlnhom15',
    storageBucket: 'btlnhom15.firebasestorage.app',
    iosBundleId: 'com.example.btlNhom15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnfEQcigtZ5n-DYJmgklEjKudDdjbGSGc',
    appId: '1:111912410978:web:4af4a558520319b610d63b',
    messagingSenderId: '111912410978',
    projectId: 'btlnhom15',
    authDomain: 'btlnhom15.firebaseapp.com',
    storageBucket: 'btlnhom15.firebasestorage.app',
    measurementId: 'G-N4H02G0MD0',
  );

}